### ISSUE TITLE
Stop Kanging!!!

### ISSUE THREAD

**Issue by chsaiujwal** [WhiteEye-Org/WhiteEyeUserBot#2]
stop Kanging other userbots. If you have fking talent, try to do it yourself. Unkang everything you kanged or serious consequences will be made.

**Comment by chsaiujwal** [comment]
Reply idiot.

**Comment by Steveultrajobs** [comment]
Fuckoff it's our wish

**Comment by Rakesh932001** [comment]
> Reply idiot.

You might be idiot not him he kept the licence same Na what's your problem let the new to grow

**Comment by Steveultrajobs** [comment]
> > Reply idiot.
> 
> You might be idiot not him he kept the licence same Na what's your problem let the new to grow

Lmao, license clearly states, you can only fork and edit the repository. You can't download and upload the repository. What an idiot you are. And you want me to let grow new people? Ofcourse I help new people group, I won't allow kangers, shitty kangers. These selfish fking kangers Kang our hard-work. When you create something and it's kanged, then you will know. Till then, shut your mouth and sleep idiot.

**Comment by chsaiujwal** [comment]
> > Reply idiot.
> 
> You might be idiot not him he kept the licence same Na what's your problem let the new to grow

Lmao, license clearly states, you can only fork and edit the repository. You can't download and upload the repository. What an idiot you are. And you want me to let grow new people? Ofcourse I help new people group, I won't allow kangers, shitty kangers. These selfish fking kangers Kang our hard-work. When you create something and it's kanged, then you will know. Till then, shut your mouth and sleep idiot.

**Comment by Rakesh932001** [comment]
> > > Reply idiot.
> > 
> > 
> > You might be idiot not him he kept the licence same Na what's your problem let the new to grow
> 
> Lmao, license clearly states, you can only fork and edit the repository. You can't download and upload the repository. What an idiot you are. And you want me to let grow new people? Ofcourse I help new people group, I won't allow kangers, shitty kangers. These selfish fking kangers Kang our hard-work. When you create something and it's kanged, then you will know. Till then, shut your mouth and sleep idiot.

You said u will help why won't u let him to do it he will learn later and do on his own why using inappropriate behaviour and words
U are an idiot 

And that license issue do u think he is the only one try to catch them first idiot
He is not even earning from your one why are u against him try to catch the real stealer u idiot 
If u can't catch sleep 😴

**Comment by chsaiujwal** [comment]
> > > > Reply idiot.
> > > 
> > > 
> > > You might be idiot not him he kept the licence same Na what's your problem let the new to grow
> > 
> > 
> > Lmao, license clearly states, you can only fork and edit the repository. You can't download and upload the repository. What an idiot you are. And you want me to let grow new people? Ofcourse I help new people group, I won't allow kangers, shitty kangers. These selfish fking kangers Kang our hard-work. When you create something and it's kanged, then you will know. Till then, shut your mouth and sleep idiot.
> 
> You said u will help why won't u let him to do it he will learn later and do on his own why using inappropriate behaviour and words
> U are an idiot
> 
> And that license issue do u think he is the only one who stole your idea try to catch them first idiot
> He is not even earning from your one why are u against him try to catch the real stealer u idiot
> If u can't catch sleep 😴

Hey fucking piece of shit, it's my fucking hard work, I don't care if he is Earning or not. I just want him to remove it. First tell him to remove it, I'll start helping him. And as I said before When you create something and it's kanged, then you will know.  Get the fuck out of here and sleep bitch.

**Comment by Rakesh932001** [comment]
> > > > > Reply idiot.
> > > > 
> > > > 
> > > > You might be idiot not him he kept the licence same Na what's your problem let the new to grow
> > > 
> > > 
> > > Lmao, license clearly states, you can only fork and edit the repository. You can't download and upload the repository. What an idiot you are. And you want me to let grow new people? Ofcourse I help new people group, I won't allow kangers, shitty kangers. These selfish fking kangers Kang our hard-work. When you create something and it's kanged, then you will know. Till then, shut your mouth and sleep idiot.
> > 
> > 
> > You said u will help why won't u let him to do it he will learn later and do on his own why using inappropriate behaviour and words
> > U are an idiot
> > And that license issue do u think he is the only one who stole your idea try to catch them first idiot
> > He is not even earning from your one why are u against him try to catch the real stealer u idiot
> > If u can't catch sleep 😴
> 
> Hey fucking piece of shit, it's my fucking hard work, I don't care if he is Earning or not. I just want him to remove it. First tell him to remove it, I'll start helping him. And as I said before When you create something and it's kanged, then you will know. Get the fuck out of here and sleep bitch.

What do you think of your self by creating one thing can you think you can scold anyone you want without any hesitation how can you use those words on anyone you want like that

First learn some manners then take to someone 

I even replied becoz u had used vulgar words first learn some respect you bitch

**Comment by chsaiujwal** [comment]
> > > > > > Reply idiot.
> > > > > 
> > > > > 
> > > > > You might be idiot not him he kept the licence same Na what's your problem let the new to grow
> > > > 
> > > > 
> > > > Lmao, license clearly states, you can only fork and edit the repository. You can't download and upload the repository. What an idiot you are. And you want me to let grow new people? Ofcourse I help new people group, I won't allow kangers, shitty kangers. These selfish fking kangers Kang our hard-work. When you create something and it's kanged, then you will know. Till then, shut your mouth and sleep idiot.
> > > 
> > > 
> > > You said u will help why won't u let him to do it he will learn later and do on his own why using inappropriate behaviour and words
> > > U are an idiot
> > > And that license issue do u think he is the only one who stole your idea try to catch them first idiot
> > > He is not even earning from your one why are u against him try to catch the real stealer u idiot
> > > If u can't catch sleep 😴
> > 
> > 
> > Hey fucking piece of shit, it's my fucking hard work, I don't care if he is Earning or not. I just want him to remove it. First tell him to remove it, I'll start helping him. And as I said before When you create something and it's kanged, then you will know. Get the fuck out of here and sleep bitch.
> 
> What do you think of your self by creating one thing can you think you can scold anyone you want without any hesitation how can you use those words on anyone you want like that
> 
> First learn some manners then talk to someone
> 
> I even replied becoz u had used vulgar words first learn some respect you bitch

Hey fucking Piece of shit, my language my wish. If you have any problem, fuck yourself or die off.  And it's my wish, I scold him for Kanging, you are his supporter, which is you are also as guilty as him. And asshole, copyright infringement is a serious matter, not your shitgane. And your fucking parents tought you only to peek your nose in others matters? What the bloody fuck. My language my wish. Fuck you asshole. Fuck you asshole. Fuck you asshole. Fuck you asshole. Fuck you asshole. Fuck you asshole. Fuck you asshole. Fuck you asshole. Fuck you asshole. Fuck you asshole. Fuck you asshole.

**Comment by chsaiujwal** [comment]
> > > > > > Reply idiot.
> > > > > 
> > > > > 
> > > > > You might be idiot not him he kept the licence same Na what's your problem let the new to grow
> > > > 
> > > > 
> > > > Lmao, license clearly states, you can only fork and edit the repository. You can't download and upload the repository. What an idiot you are. And you want me to let grow new people? Ofcourse I help new people group, I won't allow kangers, shitty kangers. These selfish fking kangers Kang our hard-work. When you create something and it's kanged, then you will know. Till then, shut your mouth and sleep idiot.
> > > 
> > > 
> > > You said u will help why won't u let him to do it he will learn later and do on his own why using inappropriate behaviour and words
> > > U are an idiot
> > > And that license issue do u think he is the only one who stole your idea try to catch them first idiot
> > > He is not even earning from your one why are u against him try to catch the real stealer u idiot
> > > If u can't catch sleep 😴
> > 
> > 
> > Hey fucking piece of shit, it's my fucking hard work, I don't care if he is Earning or not. I just want him to remove it. First tell him to remove it, I'll start helping him. And as I said before When you create something and it's kanged, then you will know. Get the fuck out of here and sleep bitch.
> 
> What do you think of your self by creating one thing can you think you can scold anyone you want without any hesitation how can you use those words on anyone you want like that
> 
> First learn some manners then talk to someone
> 
> I even replied becoz u had used vulgar words first learn some respect you bitch


I know this is your alternative ACCOUNT asshole.
Fuck you asshole. Fuck you asshole. Fuck you asshole. Fuck you asshole. Fuck you asshole. Fuck you asshole. Fuck you asshole. Fuck you asshole. Fuck you asshole. Fuck you asshole. Fuck you asshole. Fuck you asshole.

**Comment by chsaiujwal** [comment]
> > > > > > Reply idiot.
> > > > > 
> > > > > 
> > > > > You might be idiot not him he kept the licence same Na what's your problem let the new to grow
> > > > 
> > > > 
> > > > Lmao, license clearly states, you can only fork and edit the repository. You can't download and upload the repository. What an idiot you are. And you want me to let grow new people? Ofcourse I help new people group, I won't allow kangers, shitty kangers. These selfish fking kangers Kang our hard-work. When you create something and it's kanged, then you will know. Till then, shut your mouth and sleep idiot.
> > > 
> > > 
> > > You said u will help why won't u let him to do it he will learn later and do on his own why using inappropriate behaviour and words
> > > U are an idiot
> > > And that license issue do u think he is the only one who stole your idea try to catch them first idiot
> > > He is not even earning from your one why are u against him try to catch the real stealer u idiot
> > > If u can't catch sleep 😴
> > 
> > 
> > Hey fucking piece of shit, it's my fucking hard work, I don't care if he is Earning or not. I just want him to remove it. First tell him to remove it, I'll start helping him. And as I said before When you create something and it's kanged, then you will know. Get the fuck out of here and sleep bitch.
> 
> What do you think of your self by creating one thing can you think you can scold anyone you want without any hesitation how can you use those words on anyone you want like that
> 
> First learn some manners then talk to someone
> 
> I even replied becoz u had used vulgar words first learn some respect you bitch

Fucking piece of shit.

**Comment by Rakesh932001** [comment]
> > > > > > > Reply idiot.
> > > > > > 
> > > > > > 
> > > > > > You might be idiot not him he kept the licence same Na what's your problem let the new to grow
> > > > > 
> > > > > 
> > > > > Lmao, license clearly states, you can only fork and edit the repository. You can't download and upload the repository. What an idiot you are. And you want me to let grow new people? Ofcourse I help new people group, I won't allow kangers, shitty kangers. These selfish fking kangers Kang our hard-work. When you create something and it's kanged, then you will know. Till then, shut your mouth and sleep idiot.
> > > > 
> > > > 
> > > > You said u will help why won't u let him to do it he will learn later and do on his own why using inappropriate behaviour and words
> > > > U are an idiot
> > > > And that license issue do u think he is the only one who stole your idea try to catch them first idiot
> > > > He is not even earning from your one why are u against him try to catch the real stealer u idiot
> > > > If u can't catch sleep 😴
> > > 
> > > 
> > > Hey fucking piece of shit, it's my fucking hard work, I don't care if he is Earning or not. I just want him to remove it. First tell him to remove it, I'll start helping him. And as I said before When you create something and it's kanged, then you will know. Get the fuck out of here and sleep bitch.
> > 
> > 
> > What do you think of your self by creating one thing can you think you can scold anyone you want without any hesitation how can you use those words on anyone you want like that
> > First learn some manners then talk to someone
> > I even replied becoz u had used vulgar words first learn some respect you bitch
> 
> Fucking piece of shit.

Yeah you are not just a piece of shit but your are a complete shit

**Comment by chsaiujwal** [comment]
> > > > > > > > Reply idiot.
> > > > > > > 
> > > > > > > 
> > > > > > > You might be idiot not him he kept the licence same Na what's your problem let the new to grow
> > > > > > 
> > > > > > 
> > > > > > Lmao, license clearly states, you can only fork and edit the repository. You can't download and upload the repository. What an idiot you are. And you want me to let grow new people? Ofcourse I help new people group, I won't allow kangers, shitty kangers. These selfish fking kangers Kang our hard-work. When you create something and it's kanged, then you will know. Till then, shut your mouth and sleep idiot.
> > > > > 
> > > > > 
> > > > > You said u will help why won't u let him to do it he will learn later and do on his own why using inappropriate behaviour and words
> > > > > U are an idiot
> > > > > And that license issue do u think he is the only one who stole your idea try to catch them first idiot
> > > > > He is not even earning from your one why are u against him try to catch the real stealer u idiot
> > > > > If u can't catch sleep 😴
> > > > 
> > > > 
> > > > Hey fucking piece of shit, it's my fucking hard work, I don't care if he is Earning or not. I just want him to remove it. First tell him to remove it, I'll start helping him. And as I said before When you create something and it's kanged, then you will know. Get the fuck out of here and sleep bitch.
> > > 
> > > 
> > > What do you think of your self by creating one thing can you think you can scold anyone you want without any hesitation how can you use those words on anyone you want like that
> > > First learn some manners then talk to someone
> > > I even replied becoz u had used vulgar words first learn some respect you bitch
> > 
> > 
> > Fucking piece of shit.
> 
> Yeah you are not just a piece of shit but your are a complete shit

Like your parents.

**Comment by Rakesh932001** [comment]
> > > > > > > > > Reply idiot.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > You might be idiot not him he kept the licence same Na what's your problem let the new to grow
> > > > > > > 
> > > > > > > 
> > > > > > > Lmao, license clearly states, you can only fork and edit the repository. You can't download and upload the repository. What an idiot you are. And you want me to let grow new people? Ofcourse I help new people group, I won't allow kangers, shitty kangers. These selfish fking kangers Kang our hard-work. When you create something and it's kanged, then you will know. Till then, shut your mouth and sleep idiot.
> > > > > > 
> > > > > > 
> > > > > > You said u will help why won't u let him to do it he will learn later and do on his own why using inappropriate behaviour and words
> > > > > > U are an idiot
> > > > > > And that license issue do u think he is the only one who stole your idea try to catch them first idiot
> > > > > > He is not even earning from your one why are u against him try to catch the real stealer u idiot
> > > > > > If u can't catch sleep 😴
> > > > > 
> > > > > 
> > > > > Hey fucking piece of shit, it's my fucking hard work, I don't care if he is Earning or not. I just want him to remove it. First tell him to remove it, I'll start helping him. And as I said before When you create something and it's kanged, then you will know. Get the fuck out of here and sleep bitch.
> > > > 
> > > > 
> > > > What do you think of your self by creating one thing can you think you can scold anyone you want without any hesitation how can you use those words on anyone you want like that
> > > > First learn some manners then talk to someone
> > > > I even replied becoz u had used vulgar words first learn some respect you bitch
> > > 
> > > 
> > > Fucking piece of shit.
> > 
> > 
> > Yeah you are not just a piece of shit but your are a complete shit
> 
> Like your parents. 🤣😂

I didnt scolded your parents behave properly or else u will be paying a visit of my uncle and will be behind bars for inappropriate language on social media and also harassing a minor and also using unparliament language in social media sites

Did I scolded your parents why are scolding mine this is last and final warning be carefull 

Why seeing what you are shouting it will be behind bars be carefull u complete piece of shit

**Comment by chsaiujwal** [comment]
> > > > > > > > > > Reply idiot.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > You might be idiot not him he kept the licence same Na what's your problem let the new to grow
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Lmao, license clearly states, you can only fork and edit the repository. You can't download and upload the repository. What an idiot you are. And you want me to let grow new people? Ofcourse I help new people group, I won't allow kangers, shitty kangers. These selfish fking kangers Kang our hard-work. When you create something and it's kanged, then you will know. Till then, shut your mouth and sleep idiot.
> > > > > > > 
> > > > > > > 
> > > > > > > You said u will help why won't u let him to do it he will learn later and do on his own why using inappropriate behaviour and words
> > > > > > > U are an idiot
> > > > > > > And that license issue do u think he is the only one who stole your idea try to catch them first idiot
> > > > > > > He is not even earning from your one why are u against him try to catch the real stealer u idiot
> > > > > > > If u can't catch sleep 😴
> > > > > > 
> > > > > > 
> > > > > > Hey fucking piece of shit, it's my fucking hard work, I don't care if he is Earning or not. I just want him to remove it. First tell him to remove it, I'll start helping him. And as I said before When you create something and it's kanged, then you will know. Get the fuck out of here and sleep bitch.
> > > > > 
> > > > > 
> > > > > What do you think of your self by creating one thing can you think you can scold anyone you want without any hesitation how can you use those words on anyone you want like that
> > > > > First learn some manners then talk to someone
> > > > > I even replied becoz u had used vulgar words first learn some respect you bitch
> > > > 
> > > > 
> > > > Fucking piece of shit.
> > > 
> > > 
> > > Yeah you are not just a piece of shit but your are a complete shit
> > 
> > 
> > Like your parents. 🤣😂
> 
> I didnt scolded your parents behave properly or else u will be paying a visit of my uncle and will be behind bars for inappropriate language on social media and also harassing a minor and also using unparliament language in social media sites
> 
> Did I scolded your parents why are scolding mine this is last and final warning be carefull
> 
> Why seeing what you are shouting it will be behind bars be carefull u complete piece of shit

Ohhh very good, then I'll sue you guys for Kanging me. Pay me a fucking high fine. How is it asshole? Fuck your uncle too.

**Comment by Rakesh932001** [comment]
> > > > > > > > > > > Reply idiot.
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > You might be idiot not him he kept the licence same Na what's your problem let the new to grow
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Lmao, license clearly states, you can only fork and edit the repository. You can't download and upload the repository. What an idiot you are. And you want me to let grow new people? Ofcourse I help new people group, I won't allow kangers, shitty kangers. These selfish fking kangers Kang our hard-work. When you create something and it's kanged, then you will know. Till then, shut your mouth and sleep idiot.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > You said u will help why won't u let him to do it he will learn later and do on his own why using inappropriate behaviour and words
> > > > > > > > U are an idiot
> > > > > > > > And that license issue do u think he is the only one who stole your idea try to catch them first idiot
> > > > > > > > He is not even earning from your one why are u against him try to catch the real stealer u idiot
> > > > > > > > If u can't catch sleep 😴
> > > > > > > 
> > > > > > > 
> > > > > > > Hey fucking piece of shit, it's my fucking hard work, I don't care if he is Earning or not. I just want him to remove it. First tell him to remove it, I'll start helping him. And as I said before When you create something and it's kanged, then you will know. Get the fuck out of here and sleep bitch.
> > > > > > 
> > > > > > 
> > > > > > What do you think of your self by creating one thing can you think you can scold anyone you want without any hesitation how can you use those words on anyone you want like that
> > > > > > First learn some manners then talk to someone
> > > > > > I even replied becoz u had used vulgar words first learn some respect you bitch
> > > > > 
> > > > > 
> > > > > Fucking piece of shit.
> > > > 
> > > > 
> > > > Yeah you are not just a piece of shit but your are a complete shit
> > > 
> > > 
> > > Like your parents. 🤣😂
> > 
> > 
> > I didnt scolded your parents behave properly or else u will be paying a visit of my uncle and will be behind bars for inappropriate language on social media and also harassing a minor and also using unparliament language in social media sites
> > Did I scolded your parents why are scolding mine this is last and final warning be carefull
> > Why seeing what you are shouting it will be behind bars be carefull u complete piece of shit
> 
> Ohhh very good, then I'll sue you guys for Kanging me. Pay me a fucking high fine. How is it asshole? Fuck your uncle too.

😂 First got a classes of law and then come here u little fool
It is completely legal using others plugin without changing license 

Dont have a little knowledge of this and came to shout at me get lost u filthy animal

And you are now totally booked due to using a inappropriate words to a law practitioner

**Comment by Rakesh932001** [comment]
> > > > > > > > > > > > Reply idiot.
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > You might be idiot not him he kept the licence same Na what's your problem let the new to grow
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Lmao, license clearly states, you can only fork and edit the repository. You can't download and upload the repository. What an idiot you are. And you want me to let grow new people? Ofcourse I help new people group, I won't allow kangers, shitty kangers. These selfish fking kangers Kang our hard-work. When you create something and it's kanged, then you will know. Till then, shut your mouth and sleep idiot.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > You said u will help why won't u let him to do it he will learn later and do on his own why using inappropriate behaviour and words
> > > > > > > > > U are an idiot
> > > > > > > > > And that license issue do u think he is the only one who stole your idea try to catch them first idiot
> > > > > > > > > He is not even earning from your one why are u against him try to catch the real stealer u idiot
> > > > > > > > > If u can't catch sleep 😴
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Hey fucking piece of shit, it's my fucking hard work, I don't care if he is Earning or not. I just want him to remove it. First tell him to remove it, I'll start helping him. And as I said before When you create something and it's kanged, then you will know. Get the fuck out of here and sleep bitch.
> > > > > > > 
> > > > > > > 
> > > > > > > What do you think of your self by creating one thing can you think you can scold anyone you want without any hesitation how can you use those words on anyone you want like that
> > > > > > > First learn some manners then talk to someone
> > > > > > > I even replied becoz u had used vulgar words first learn some respect you bitch
> > > > > > 
> > > > > > 
> > > > > > Fucking piece of shit.
> > > > > 
> > > > > 
> > > > > Yeah you are not just a piece of shit but your are a complete shit
> > > > 
> > > > 
> > > > Like your parents. 🤣😂
> > > 
> > > 
> > > I didnt scolded your parents behave properly or else u will be paying a visit of my uncle and will be behind bars for inappropriate language on social media and also harassing a minor and also using unparliament language in social media sites
> > > Did I scolded your parents why are scolding mine this is last and final warning be carefull
> > > Why seeing what you are shouting it will be behind bars be carefull u complete piece of shit
> > 
> > 
> > Ohhh very good, then I'll sue you guys for Kanging me. Pay me a fucking high fine. How is it asshole? Fuck your uncle too.
> 
> 😂 First got a classes of law and then come here u little fool
> It is completely legal using others plugin without changing license
> 
> Dont have a little knowledge of this and came to shout at me get lost u filthy animal
> 
> And you are now totally booked due to using a inappropriate words to a law practitioner

If you have enough guts to defend don't edit the message 
If you are feared edit your message little child and got to your parents and cry

**Comment by chsaiujwal** [comment]
> > > > > > > > > > > > Reply idiot.
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > You might be idiot not him he kept the licence same Na what's your problem let the new to grow
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Lmao, license clearly states, you can only fork and edit the repository. You can't download and upload the repository. What an idiot you are. And you want me to let grow new people? Ofcourse I help new people group, I won't allow kangers, shitty kangers. These selfish fking kangers Kang our hard-work. When you create something and it's kanged, then you will know. Till then, shut your mouth and sleep idiot.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > You said u will help why won't u let him to do it he will learn later and do on his own why using inappropriate behaviour and words
> > > > > > > > > U are an idiot
> > > > > > > > > And that license issue do u think he is the only one who stole your idea try to catch them first idiot
> > > > > > > > > He is not even earning from your one why are u against him try to catch the real stealer u idiot
> > > > > > > > > If u can't catch sleep 😴
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Hey fucking piece of shit, it's my fucking hard work, I don't care if he is Earning or not. I just want him to remove it. First tell him to remove it, I'll start helping him. And as I said before When you create something and it's kanged, then you will know. Get the fuck out of here and sleep bitch.
> > > > > > > 
> > > > > > > 
> > > > > > > What do you think of your self by creating one thing can you think you can scold anyone you want without any hesitation how can you use those words on anyone you want like that
> > > > > > > First learn some manners then talk to someone
> > > > > > > I even replied becoz u had used vulgar words first learn some respect you bitch
> > > > > > 
> > > > > > 
> > > > > > Fucking piece of shit.
> > > > > 
> > > > > 
> > > > > Yeah you are not just a piece of shit but your are a complete shit
> > > > 
> > > > 
> > > > Like your parents. 🤣😂
> > > 
> > > 
> > > I didnt scolded your parents behave properly or else u will be paying a visit of my uncle and will be behind bars for inappropriate language on social media and also harassing a minor and also using unparliament language in social media sites
> > > Did I scolded your parents why are scolding mine this is last and final warning be carefull
> > > Why seeing what you are shouting it will be behind bars be carefull u complete piece of shit
> > 
> > 
> > Ohhh very good, then I'll sue you guys for Kanging me. Pay me a fucking high fine. How is it asshole? Fuck your uncle too.
> 
> 😂 First got a classes of law and then come here u little fool
> It is completely legal using others plugin without changing license
> 
> Dont have a little knowledge of this and came to shout at me get lost u filthy animal
> 
> And you are now totally booked due to using a inappropriate words to a law practitioner

Lol don't teach me shitty law here. According to GitHub dcma, you can only edit the repository if you fork it. Without forking it, you can't do shit.

**Comment by Rakesh932001** [comment]
> > > > > > > > > > > > > Reply idiot.
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > You might be idiot not him he kept the licence same Na what's your problem let the new to grow
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > Lmao, license clearly states, you can only fork and edit the repository. You can't download and upload the repository. What an idiot you are. And you want me to let grow new people? Ofcourse I help new people group, I won't allow kangers, shitty kangers. These selfish fking kangers Kang our hard-work. When you create something and it's kanged, then you will know. Till then, shut your mouth and sleep idiot.
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > You said u will help why won't u let him to do it he will learn later and do on his own why using inappropriate behaviour and words
> > > > > > > > > > U are an idiot
> > > > > > > > > > And that license issue do u think he is the only one who stole your idea try to catch them first idiot
> > > > > > > > > > He is not even earning from your one why are u against him try to catch the real stealer u idiot
> > > > > > > > > > If u can't catch sleep 😴
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Hey fucking piece of shit, it's my fucking hard work, I don't care if he is Earning or not. I just want him to remove it. First tell him to remove it, I'll start helping him. And as I said before When you create something and it's kanged, then you will know. Get the fuck out of here and sleep bitch.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > What do you think of your self by creating one thing can you think you can scold anyone you want without any hesitation how can you use those words on anyone you want like that
> > > > > > > > First learn some manners then talk to someone
> > > > > > > > I even replied becoz u had used vulgar words first learn some respect you bitch
> > > > > > > 
> > > > > > > 
> > > > > > > Fucking piece of shit.
> > > > > > 
> > > > > > 
> > > > > > Yeah you are not just a piece of shit but your are a complete shit
> > > > > 
> > > > > 
> > > > > Like your parents. 🤣😂
> > > > 
> > > > 
> > > > I didnt scolded your parents behave properly or else u will be paying a visit of my uncle and will be behind bars for inappropriate language on social media and also harassing a minor and also using unparliament language in social media sites
> > > > Did I scolded your parents why are scolding mine this is last and final warning be carefull
> > > > Why seeing what you are shouting it will be behind bars be carefull u complete piece of shit
> > > 
> > > 
> > > Ohhh very good, then I'll sue you guys for Kanging me. Pay me a fucking high fine. How is it asshole? Fuck your uncle too.
> > 
> > 
> > 😂 First got a classes of law and then come here u little fool
> > It is completely legal using others plugin without changing license
> > Dont have a little knowledge of this and came to shout at me get lost u filthy animal
> > And you are now totally booked due to using a inappropriate words to a law practitioner
> 
> Lol don't teach me shitty law here. According to GitHub dcma, you can only edit the repository if you fork it. Without forking it, you can't do shit.

Will you recheck once

**Comment by chsaiujwal** [comment]
> > > > > > > > > > > > > > Reply idiot.
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 
> > > > > > > > > > > > > You might be idiot not him he kept the licence same Na what's your problem let the new to grow
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > Lmao, license clearly states, you can only fork and edit the repository. You can't download and upload the repository. What an idiot you are. And you want me to let grow new people? Ofcourse I help new people group, I won't allow kangers, shitty kangers. These selfish fking kangers Kang our hard-work. When you create something and it's kanged, then you will know. Till then, shut your mouth and sleep idiot.
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > You said u will help why won't u let him to do it he will learn later and do on his own why using inappropriate behaviour and words
> > > > > > > > > > > U are an idiot
> > > > > > > > > > > And that license issue do u think he is the only one who stole your idea try to catch them first idiot
> > > > > > > > > > > He is not even earning from your one why are u against him try to catch the real stealer u idiot
> > > > > > > > > > > If u can't catch sleep 😴
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Hey fucking piece of shit, it's my fucking hard work, I don't care if he is Earning or not. I just want him to remove it. First tell him to remove it, I'll start helping him. And as I said before When you create something and it's kanged, then you will know. Get the fuck out of here and sleep bitch.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > What do you think of your self by creating one thing can you think you can scold anyone you want without any hesitation how can you use those words on anyone you want like that
> > > > > > > > > First learn some manners then talk to someone
> > > > > > > > > I even replied becoz u had used vulgar words first learn some respect you bitch
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Fucking piece of shit.
> > > > > > > 
> > > > > > > 
> > > > > > > Yeah you are not just a piece of shit but your are a complete shit
> > > > > > 
> > > > > > 
> > > > > > Like your parents. 🤣😂
> > > > > 
> > > > > 
> > > > > I didnt scolded your parents behave properly or else u will be paying a visit of my uncle and will be behind bars for inappropriate language on social media and also harassing a minor and also using unparliament language in social media sites
> > > > > Did I scolded your parents why are scolding mine this is last and final warning be carefull
> > > > > Why seeing what you are shouting it will be behind bars be carefull u complete piece of shit
> > > > 
> > > > 
> > > > Ohhh very good, then I'll sue you guys for Kanging me. Pay me a fucking high fine. How is it asshole? Fuck your uncle too.
> > > 
> > > 
> > > 😂 First got a classes of law and then come here u little fool
> > > It is completely legal using others plugin without changing license
> > > Dont have a little knowledge of this and came to shout at me get lost u filthy animal
> > > And you are now totally booked due to using a inappropriate words to a law practitioner
> > 
> > 
> > Lol don't teach me shitty law here. According to GitHub dcma, you can only edit the repository if you fork it. Without forking it, you can't do shit.
> 
> Will you recheck once

I read both GPL and takedown policy.
